apiVersion: kubeadm.k8s.io/v1beta2
caCertPath: /etc/kubernetes/pki/ca.crt
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.1.22:8443
    caCertHashes:
    - sha256:7495830a745a99661f3a1e05d852bcd652a9fb9034f3554b575d612fa1644d3f
    token: u47rrg.fwe4whsdlqdfvhdh
  timeout: 5m0s
  tlsBootstrapToken: u47rrg.fwe4whsdlqdfvhdh
nodeRegistration:
  name: worker01
  kubeletExtraArgs:
    node-ip: 192.168.1.23
